#!/usr/bin/env bash
set -e

# cd to your config dir
pushd ~/nixos/

# Early return if no changes were detected (thanks @singiamtel!)
if git diff --quiet '*.nix'; then
    echo "No changes detected, exiting."
    popd
    exit 0
fi

# Autoformat your nix files
alejandra . &>/dev/null \
  || ( alejandra . ; echo "formatting failed!" && exit 1)

# Shows your changes
git diff -U0 '*.nix'

echo "NixOS Rebuilding..."

# Rebuild, output simplified errors, log trackebacks
# sudo nixos-rebuild switch --flake $HOME/nixos#$(hostname) &>nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)
nix-on-droid switch --flake $HOME/nixos &>nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)

# no list-generation, so commit is manual

popd

echo Done!
