{pkgs, ...}: {
  home.packages = with pkgs; [
    # Whatever home-manager package resides here (Which is most)
    wineWowPackages.staging
    dfu-util
    avrdude
    avrdudess
    qmk
    vial
    jdk
    prismlauncher
    gnome-extension-manager
    bat
    jq
    mindustry
    alacritty
    protonup-ng
    bottles
    htop
    wakatime-cli
    flameshot
    ffmpeg
    vlc
    obs-studio
    sdkmanager
    android-tools
    figma-linux
    gallery-dl
    yt-dlp
    p7zip
    nix-init
    nixpkgs-fmt
    nixpkgs-review
    pcsx2
    steam-rom-manager
    bambu-studio
    ckan
    fsearch
    mpv-unwrapped
    imv
    openscad
  ];
}
